### ISSUE TITLE
Machoc uses murmurhash

### ISSUE THREAD

**Issue by tpo-anssi** [0x00ach/idadiff#1]
The machoc algorithm implementation in Polichombr uses the Murmurhash3 hash function instead of MD5,
so the calculated hashes from the script are differents

**Comment by 0x00-lol** [comment]
I know, I'm too lazy for now, I'll keep the old one for a while :') 

(mmh3 is not available in my actual IDA Pro version)
(also nobody seems to use the script since there are lots of bugs I did not patch, and still no complains)
